### ISSUE TITLE
The Camera

### ISSUE THREAD

**Issue by MinT-Napkin** [MinT-Napkin/Umbrella-Weather#2]
The camera follows the player object as the player moves

Details:

- The camera follows the player object's transform position as it moves
- Could be upgraded later on, for now, it's just a simple camera follow script
- Ideally 1 Person
- Very good camera video if you want to do this type of camera: https://www.youtube.com/watch?v=yaQlRvHgIvE&t=1s 
- Don't forget to commit changes within in your own branch + your own testing scene to avoid merge conflicts

**Comment by Kestrel86** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    public Transform target;
    public Vector3 offset;

    [Range(1,10)]
    public float smoothFactor;

    // Update is called once per frame
    private void FixedUpdate()
    {
        Follow();
    }

    void Follow()
    {
        Vector3 targetPosition = target.position + offset;

        Vector3 smoothPosition = Vector3.Lerp(transform.position, targetPosition, smoothFactor * Time.deltaTime);

        transform.position = smoothPosition;
    }
}
